# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    container_name: doctuch_pos_frontend
    ports:
      - "3000:3000"    # mapping container 3000 to host 3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: npm run dev
