version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend-pos-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        expose:
            - 9000
        depends_on:
            - mysql-db

    nginx:
        image: nginx:latest
        container_name: nginx-server
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: doctuch_pos_db
            MYSQL_USER: doctuch_pos
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
